# Object Detection Configuration
detection:
  # Contour detection parameters
  contour:
    min_area: 300          # Minimum contour area (reduced for smaller objects)
    max_area: 25000        # Maximum contour area (reduced for better accuracy)
    blur_kernel_size: 3    # Gaussian blur kernel size (smaller for sharper detection)
    morph_kernel_size: 3   # Morphological operations kernel size (smaller for precision)
  
  # Image preprocessing parameters
  preprocessing:
    bilateral_filter:
      d: 9                 # Diameter of pixel neighborhood
      sigma_color: 75      # Filter sigma in color space
      sigma_space: 75      # Filter sigma in coordinate space
    
    adaptive_threshold:
      max_value: 255       # Maximum value assigned to pixel
      block_size: 11       # Size of neighborhood area
      c: 2                 # Constant subtracted from mean

# Camera configuration
camera:
  index: 0               # Camera index (0 for default camera)
  width: 640             # Frame width
  height: 480            # Frame height
  fps: 30                # Frames per second

# Display configuration
display:
  window_name: "Object Color & Shape Detector"
  show_contours: true    # Show object contours
  show_bounding_boxes: true  # Show bounding boxes
  show_color_labels: true    # Show color labels
  show_shape_labels: true    # Show shape labels
  font_scale: 0.6        # Text font scale (reduced for multiple labels)
  line_thickness: 2      # Line thickness for drawings
